

dataset:  
  CMUMOSEI:
    dataset_path: None
    data : mosei_senti
    if_align: false
    classes: 2  
    validation: True
    audio:  
      input_dim: 74
    visual:
      input_dim: 35 
    text:
      input_dim: 300

  FOOD101:
    targ_dir: None
    dataset_path: None
    classes: 101
    validation: false
    text:
      input_dim: 40
    visual:
      input_dim: 224
  
  UCF101:
    classes: 101
    validation: false
    stat_path : None
    train_txt : None
    test_txt : None
    visual_path : None
    flow_path_v : None
    flow_path_u : None
    flow:
      input_dim: 224
    visual:
      input_dim: 224

  
  Balance:
    csv_path: None
    visual_path: None
    audio_path: None
    validation: false
    classes: 30  
    audio:
      input_dim: None
    visual:
      input_dim: None
  
  CREMAD:
    classes: 6
    fps: 2
    visual_path : None
    audio_path : None
    stat_path : None
    train_txt : None
    test_txt : None
    validation: false
    audio:
      input_dim: None
    visual:
      input_dim: None

  KineticsSounds:
    csv_path_train: None
    visual_path_train: None
    audio_path_train: None
    csv_path_test: None
    visual_path_test: None
    audio_path_test: None
    validation: false
    classes: 31  
    audio:
      input_dim: None
    visual:
      input_dim: None
  VGGSound:
    validation: false
    classes: 309
    use_video_frames: 3
    csv_root: None
    video_train_root: None
    video_test_root: None
    audio_train_root: None
    audio_test_root: None
    audio:
      input_dim: None
    visual:
      input_dim: None
