
Transformer:
  if_pretrain: True
  pretrain_path: '/data/users/shaoxuan_xu/menglucui/UMPC_Food/Pretrained_model/dataroot/models/google-bert/bert-base-uncased'
  output_dim: 1024
  audio:
    n_features: 512
    dim: 1024
    n_head: 4
    n_layers: 2
  visual:
    n_features: 512
    dim: 1024
    n_head: 4
    n_layers: 2
  text:
    n_features: 512
    dim: 1024
    n_head: 4
    n_layers: 2
ResNet18:
  output_dim: 512
  if_pretrain: True
  pretrain_path: '/data/users/shaoxuan_xu/3_OGM/Pretrained_model/resnet18.pth'
  audio:
    modality: 'audio'
  visual:
    modality: 'visual'
  flow:
    modality: 'flow'