model:
  BaseClassifier:
    encoders: {audio: Transformer_, visual: Transformer_, text:  Transformer_}
    fusion: "concat"
    modality_size: 1024
  BaseClassifier_AMCo:
    encoders: {audio: ResNet18, visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_Greedy:
    encoders: {audio: ResNet18, visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_MLA:
    encoders: {audio: ResNet18, visual: ResNet18}
    fusion: "shared"
    modality_size: 1024
    # If use Transformer as encoder, set the modality_size to 1024. If use ResNet18 as encoder, set the modality_size to 512.
  BaseClassifier_ReconBoost:
    encoders: {audio: ResNet18, visual: ResNet18}
    fusion: "shared"
    modality_size: 1024
# expand other configuration of fusion methods
fusion:
  concat:
    out_put_dim: 100
  shared:
    out_put_dim: 100