model:
  BaseClassifier:
    encoders: {front_view: ResNet18, back_view: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_AMCo:
    encoders: {front_view: ResNet18, back_view: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_Greedy:
    encoders: {front_view: ResNet18, back_view: ResNet18}
    fusion: "concat"
    modality_size: 512
  # encoder名字的规范化 更多的encoder official的encoder
fusion:
  concat:
    out_put_dim: 100