model:
  BaseClassifier:
    encoders: {audio: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_AMCo:
    encoders: {audio: ResNet18,visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_Greedy:
    encoders: {audio: ResNet18,visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_MLA:
    encoders: {audio: Transformer_,visual: Transformer_, text: Transformer_}
    fusion: "shared"
    modality_size: 1024
  BaseClassifier_ReconBoost:
    encoders: {audio: Transformer_,visual: Transformer_, text: Transformer_}
    fusion: "shared"
    modality_size: 1024
  # encoder名字的规范化 更多的encoder official的encoder
fusion:
  concat:
    out_put_dim: 100
  shared:
    out_put_dim: 100