model:
  BaseClassifier:
    encoders: {visual: ResNet18, audio: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_AMCo:
    encoders: {flow: ResNet18, visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  # encoder名字的规范化 更多的encoder official的encoder
fusion:
  concat:
    out_put_dim: 100