model:
  BaseClassifier:
    encoders: {audio: ResNet18, visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  BaseClassifier_AMCo:
    encoders: {text: Transformer, visual: ResNet18}
    fusion: "concat"
    modality_size: 512
  
fusion:
  concat:
    out_put_dim: 100