mode: "train_and_test"
check_point_path: ''

seed: 42
Main_config:
  model: "BaseClassifier" #
  model: "BaseClassifier" #
  tasks: "Classifier" #
  trainer: "LinearProbeTrainer"
  device: '1'
  dataset: CREMAD

Train:
  dataset: CREMAD


Test:
  dataset: CREMAD

