name: "Baseline-CREMAD"
mode: "train_and_test"
seed: 42

dataset:
  dataloader:
    eff_batch_size: 64
    num_workers: 4 # number of workers for dataloader
    fast_run: false # if true, only use part of the dataset
    shuffle: true # if true, shuffle the dataset
    drop_last: true # if true, drop the last batch if the size is not equal to batch_size
    pin_memory: true # if true, use pin_memory for dataloader
  train:
    name: Cremad
    mode: train
    fps: 3
    audio_path: D:\Data\cremad\audio
    visual_path: D:\Data\cremad\visual
    csv_file: D:\Data\cremad\train.csv
  test:
    name: Cremad
    mode: test
    fps: 3
    audio_path: D:\Data\cremad\audio
    visual_path: D:\Data\cremad\visual
    csv_file: D:\Data\cremad\test.csv
